version: "3"

services:
  postgres_db:
    image: postgres
    container_name: order_svc_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - restaurant_db:/var/lib/postgresql
      - restaurant_db_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
volumes:
  restaurant_db:
  restaurant_db_data:
